export const ADD_TRAINING = 'ADD_TRAINING';
export const DELETE_TRAINING = 'DELETE_TRAINING';
export const CHANGE_TRAININGS = 'CHANGE_TRAININGS';
export const SET_SELECTED_TRAINING = 'SET_SELECTED_TRAINING';
export const ADD_EXERCISE_KEY = 'ADD_EXERCISE_KEY';
export const DELETE_EXERCISE_KEY = 'DELETE_EXERCISE_KEY';
