export const SHOW_EXERCISES = 'SHOW_EXERCISES';
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const ADD_SET = 'ADD_SET';
export const DELETE_SET = 'DELETE_SET';
export const SAVE_EXERCISE_CHANGES = 'SAVE_EXERCISE_CHANGES';
